### ISSUE TITLE
ffmpeg : cannot open shared library error!

### ISSUE THREAD

**Issue by AkhilSinghRana** [boozyguo/ClearWave#2]
Hi,

While running your code for inference I am getting the error below:
"./ffmpeg: error while loading shared libraries: libavdevice-ffmpeg.so.56: cannot open shared object file: No such file or directory
[DEBUG] WebRtcNs_denoise_initaaa:0 [DEBUG] WebRtcNs_denoise_initbbb:0 [DEBUG] WebRtcNs_denoise_initcccc:0 
failed to open pcm
./ffmpeg: error while loading shared libraries: libavdevice-ffmpeg.so.56: cannot open shared object file: No such file or directory
rm: cannot remove ‘./demo_workspace/enh_wavs/test/1000db/TEST_DR7_FCAU0_sx317.noise1.wav.enh.pcm’: No such file or directory"

Any advice on how to resolve this?

Thanks,
AKhil

**Comment by boozyguo** [comment]
hello, AKhil
maybe you can try 
sudo apt install ffmpeg
