### ISSUE TITLE
can't download the pre-trained model

### ISSUE THREAD

**Issue by sehsanh** [boozyguo/ClearWave#3]
Hello,
I wanted to test the learned model on my data ,but I was't able to download it from your source. Is there another way for accessing the pre-trained model?

Thank you,
Ehsan

**Comment by boozyguo** [comment]
please download the base dnn model from https://pan.baidu.com/s/1eVnRkNb5xIn96aYOV8C-Gg and copy the .h5 file to ./models/pretrained/base_dnn_model.h5.

**Comment by Iko2023** [comment]
It is not possible to download the .h5 file without a Baidu account, which cannot be created in many countries.
Could you provide an alternate download link?
